version: '3.2'
services:
  server:
    build: ./server
    ports:
     - "4201:4201"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    command: ["/wait-for-it.sh", "db:3306", "--", "node", "/app/index.js"]
  db:
    build: ./database
